project:
  type: website
  resources:
  - CNAME

website:
  title: "Identités numériques 2024-2025"
  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - posts/bibliographie.qmd
      - section: "Séances de cours"
        contents:
          - posts/220125.qmd
          - posts/290125.qmd
#          - posts/050225.qmd
#          - posts/120225.qmd
#          - posts/190225.qmd
#          - posts/050325.qmd
#          - posts/120325.qmd
#          - posts/190325.qmd
#          - posts/260325.qmd
#          - posts/020425.qmd
#          - posts/090425.qmd
#          - posts/230425.qmd
      - section: "Outils"
        contents:
          #          - tools/escriptorium.qmd
#          - tools/gephi.qmd
          #          - tools/git.qmd
          #          - tools/hypothesis.qmd
          #          - tools/isidore.qmd
          #          - tools/omeka.qmd
          #          - tools/opentheso.qmd
          - tools/redaction.qmd
#          - tools/stylo.qmd
#          - tools/terminal.qmd
  #          - tools/voyant-tools.qmd
  #          - tools/zotero.qmd
  page-footer:
    left: "© 2025 WTFPL, Roch Delannay"
    right: "Ce site a été réalisé avec [Quarto](https://quarto.org)"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
