---
title: "14 février 2024"
bibliography: ../bibliographie/bibliographie.bib
nocite: false
---

## Fabrication d'un portrait

::: {.callout-note}

[Cliquez ici](https://demo.hedgedoc.org/0DrmK7suTxqE0Zae8BC5KA#) pour accéder au pad collaboratif.

:::

## Consigne

Pendant le cours : 

1. Travailler en binôme
2. Chaque binôme devra réaliser un portrait. Les portraits seront à déposer sur la plateforme https://coursenligne.parisnanterre.fr pour le **14 février 2024** au plus tard à **23h59**.

::: {.callout-important}

### Trinômes

Pour celles et ceux qui souhaitent former des trinômes : 

- le portrait devra mettre en perspective deux techniques de réalisation différentes (deux objets à rendre) ;

:::

## Pour le 28 février

1. Il est également demandé à chaque binôme d'écrire un résumé critique du processus d'élaboration du portrait en lien avec les notions du cours (**4000 signes espaces compris**), à rendre pour le **28 février 2024**. Ce texte doit également être déposé sur coursenligne.

::: {.callout-important}

### Trinômes

Pour celles et ceux qui souhaitent former des trinômes : 

- le résumé critique devra comprendre cette nouvelle dimension et passe de 4000 à **6000 signes espaces compris**.

:::

2. Lire : 

- [@georges_identite_2011]